# Generated by Django 3.1.5 on 2021-02-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
    ]
