# Generated by Django 3.1.5 on 2021-02-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=10, verbose_name='username')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thoughts', models.TextField(verbose_name='Thoughts')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='Person.person')),
            ],
        ),
    ]
